# Permalinks
permalink:           pretty

# Setup
title:               Cross Timbers Twilight Camp
tagline:             Cross Timbers District, Longhorn Council, BSA
url:                 https://ctdaycamp.github.io
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Cross Timbers District, Longhorn Council, BSA
  url:               https://www.crosstimbersdistrict.org
  email:            crosstimbersdaycamp@gmail.com

pages_list:       
  News: '/news'
  Date: '/date'
  Location: '/location'
  Unit Info: '/units'
  Family Info: '/families'
  Registration: '/registration'


# Custom vars
version:             2.0.0
github:
repo:                https://github.com/CrossTimbersDayCamp/ctdaycamp.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
